# Ruby Console for Ollama

FROM ruby:3.4.8-trixie

# Install some barebone dev stuff for convenince when in console
RUN apt-get update && apt-get install -y build-essential git libyaml-dev libpq-dev curl wget vim nano

# Set up gems
# COPY Gemfile Gemfile.lock ./

# RUN gem install bundler && bundle install --jobs 20 --retry 5
